In [1]:
import torch
import numpy as np

# Episode 0: PyTorch Basics

**Goal**: Understand the fundamental data structure used in all modern deep learning

---

## The Core Concept - Tensors

- **Tensor** = Multi-dimensional array (generalization of matrices)
- Examples:
  - Scalar (0D): `5`
  - Vector (1D): `[1, 2, 3]`
  - Matrix (2D): `[[1, 2], [3, 4]]`
  - 3D Tensor: `[[[...], [...]], [[...], [...]]]`
  
**In NLP**: Text → Numbers → Tensors → Neural Net → Predictions

---

## Part 1: Creating Tensors

Let's create tensors in different ways and understand their shapes.

In [11]:
# From a Python list to a PyTorch tensor

tensor_1d = torch.tensor([1, 2, 3, 4, 5])

print(f"1D Tensor (vector): {tensor_1d}")
print(f"Shape: {tensor_1d.shape}")

1D Tensor (vector): tensor([1, 2, 3, 4, 5])
Shape: torch.Size([5])


In [3]:
# 2D Tensor (matrix)
tensor_2d = torch.tensor([[1, 2, 3],
                          [4, 5, 6]])
print(f"2D Tensor (matrix):\n{tensor_2d}")
print(f"Shape: {tensor_2d.shape}")  # [rows, columns]

2D Tensor (matrix):
tensor([[1, 2, 3],
        [4, 5, 6]])
Shape: torch.Size([2, 3])


In [4]:
# Random tensors (common for initializing neural network weights)
random_tensor = torch.randn(3, 4)  # 3 rows, 4 columns, random normal distribution
print(f"Random tensor (3x4):\n{random_tensor}")

Random tensor (3x4):
tensor([[ 1.8304,  1.8932, -2.3468, -0.3667],
        [-1.0621, -0.3295, -1.4641,  1.4169],
        [ 1.0241, -0.2773,  0.1790, -1.7904]])


In [5]:
# Zeros and ones (common for initialization)
zeros = torch.zeros(2, 3)
ones = torch.ones(2, 3)
print(f"Zeros (2x3):\n{zeros}")
print(f"\nOnes (2x3):\n{ones}")

Zeros (2x3):
tensor([[0., 0., 0.],
        [0., 0., 0.]])

Ones (2x3):
tensor([[1., 1., 1.],
        [1., 1., 1.]])


---

## Part 2: Basic Operations

Neural networks are built on tensor operations - especially matrix multiplication!

In [6]:
# Element-wise operations
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])

print(f"a = {a}")
print(f"b = {b}")
print(f"\na + b = {a + b}")
print(f"a * b = {a * b}")  # Element-wise multiplication
print(f"a ** 2 = {a ** 2}")

a = tensor([1., 2., 3.])
b = tensor([4., 5., 6.])

a + b = tensor([5., 7., 9.])
a * b = tensor([ 4., 10., 18.])
a ** 2 = tensor([1., 4., 9.])


In [7]:
# Dot product
dot_product = torch.dot(a, b)
print(f"Dot product (a · b) = {dot_product}")

Dot product (a · b) = 32.0


In [8]:
# Matrix multiplication (the backbone of neural networks!)
matrix_a = torch.tensor([[1.0, 2.0],
                         [3.0, 4.0]])
matrix_b = torch.tensor([[5.0, 6.0],
                         [7.0, 8.0]])

result = torch.mm(matrix_a, matrix_b)  # or use @ operator

print(f"Matrix A:\n{matrix_a}")
print(f"\nMatrix B:\n{matrix_b}")
print(f"\nA @ B (matrix multiplication):\n{result}")

Matrix A:
tensor([[1., 2.],
        [3., 4.]])

Matrix B:
tensor([[5., 6.],
        [7., 8.]])

A @ B (matrix multiplication):
tensor([[19., 22.],
        [43., 50.]])


---

## Part 3: Automatic Differentiation (Gradient computation)

**This is why PyTorch exists** - it computes gradients automatically (see "Gradient Descent" and "Backprop" in ML course)

This is what makes training neural networks possible. Without automatic differentiation, we'd have to compute all derivatives by hand!

In [9]:
# Enable gradient tracking
x = torch.tensor(2.0, requires_grad=True)
y = torch.tensor(3.0, requires_grad=True)

# Compute function: z = x^2 + 2xy + y^2
z = x**2 + 2*x*y + y**2

print(f"x = {x.item()}")
print(f"y = {y.item()}")
print(f"z = x² + 2xy + y² = {z.item()}")

x = 2.0
y = 3.0
z = x² + 2xy + y² = 25.0


In [10]:
# Compute gradients
z.backward()  # Automatic differentiation!

print(f"∂z/∂x = {x.grad.item()}")  # Should be 2x + 2y = 2(2) + 2(3) = 10
print(f"∂z/∂y = {y.grad.item()}")  # Should be 2x + 2y = 2(2) + 2(3) = 10

print("\nPyTorch computed these gradients automatically!")
print("This is what makes training neural networks possible.")

∂z/∂x = 10.0
∂z/∂y = 10.0

PyTorch computed these gradients automatically!
This is what makes training neural networks possible.


---

## Episode 0 Summary

### What We Learned:

**Tensors** are multi-dimensional arrays  
**PyTorch** provides fast operations on tensors  
**Automatic differentiation** enables backpropagation  

### What's Next:

In the next episode, we'll use these tools to build a simple classifier

### Key Takeaway

**PyTorch handles the math. You focus on the architecture.**